### PR TITLE
first draft of mobile responsive layout based on iPhone 5

### PR DESCRIPTION
**Pull request by PaulHowley**

### CODE REVIEW

**Comment by PaulHowley** [comment]
Screenshot as follows:
image

**Comment by krisquigley** [comment]
In terms of the design, I would add a bit more padding around the search and lucky buttons so that they are bigger

**Review by krisquigley — COMMENTED** [review]
In terms of the design, I would add a bit more padding around the search and lucky buttons so that they are bigger

**Comment by PaulHowley** [comment]
Kris, please see updated code with media queries and screenshots below:
image

image

image


image

**Review by krisquigley — APPROVED** [review]

**Pull request merged**
